### ISSUE TITLE
Array as input parameter?

### ISSUE THREAD

**Issue by Gargo** [kevin0571/Dratini#2]
I need the following:
```
struct LogInParameters: URLEncodedBodyData {
    let username: String
    let fields: [String]
}
```

**Comment by kevin-lyn** [comment]
@Gargo It's by default supported and it will be encoded into:
```
/// Array parameter - key: [1,2,3] will be converted to:
/// key[]=1&key[]=2&key[]=3
```
If you want a different encoding, you could implement your own body data encoding by conforming to `BodyData`.

**Comment by gerchicov-bp** [comment]
@kevin0571 
NO. For example aliexpress can accept an array as **One** parameter:
key1=1,2,3&key2=...
And as I understand other APIs can parse such arrays in their own way

**Comment by kevin-lyn** [comment]
@gerchicov-bp in that case you could declare `key1` as string, and pass in the common separated string. Or you could implement your own BodyData or QueryString. See: https://github.com/kevin0571/Dratini#customization
